# Generated by Django 5.2.7 on 2025-10-06 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('web', 'Website'), ('api', 'API'), ('pdf', 'PDF Direto'), ('rss', 'RSS Feed')], max_length=20)),
                ('url_base', models.URLField(max_length=500)),
                ('frequencia_coleta', models.CharField(default='diaria', help_text='Ex: diaria, semanal, mensal', max_length=50)),
                ('scraper_class', models.CharField(help_text='Nome da classe Python do scraper (ex: CositScraper)', max_length=200)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('erro', 'Com Erro')], default='ativo', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultima_coleta', models.DateTimeField(blank=True, null=True)),
                ('proxima_coleta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fonte de Dados',
                'verbose_name_plural': 'Fontes de Dados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('tipo_documento', models.CharField(choices=[('lei', 'Lei'), ('resolucao', 'Resolução'), ('consulta', 'Solução de Consulta'), ('pergunta', 'Pergunta e Resposta'), ('ato', 'Ato Declaratório'), ('outro', 'Outro')], max_length=50)),
                ('url_origem', models.URLField(max_length=1000)),
                ('identificador_externo', models.CharField(blank=True, help_text='ID do documento no site de origem', max_length=200)),
                ('hash_conteudo', models.CharField(help_text='SHA256 do conteúdo bruto para detectar mudanças', max_length=64)),
                ('caminho_arquivo', models.CharField(help_text='Caminho relativo em /data/raw/', max_length=500)),
                ('tamanho_bytes', models.IntegerField(default=0)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=200)),
                ('numero_documento', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('coletado', 'Coletado'), ('processando', 'Processando'), ('processado', 'Processado'), ('erro', 'Erro')], default='coletado', max_length=20)),
                ('versao', models.IntegerField(default=1)),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='coleta.fontedados')),
            ],
            options={
                'verbose_name': 'Documento Fonte',
                'verbose_name_plural': 'Documentos Fonte',
                'ordering': ['-coletado_em'],
                'indexes': [models.Index(fields=['fonte', 'status'], name='coleta_docu_fonte_i_86b608_idx'), models.Index(fields=['hash_conteudo'], name='coleta_docu_hash_co_5a89ec_idx'), models.Index(fields=['-coletado_em'], name='coleta_docu_coletad_56d631_idx')],
                'unique_together': {('fonte', 'identificador_externo')},
            },
        ),
        migrations.CreateModel(
            name='LogColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(blank=True, null=True)),
                ('documentos_novos', models.IntegerField(default=0)),
                ('documentos_atualizados', models.IntegerField(default=0)),
                ('documentos_ignorados', models.IntegerField(default=0)),
                ('documentos_erro', models.IntegerField(default=0)),
                ('mensagem', models.TextField(blank=True)),
                ('erro_detalhe', models.TextField(blank=True)),
                ('metadados', models.JSONField(blank=True, default=dict, help_text='Dados adicionais em JSON')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='coleta.fontedados')),
            ],
            options={
                'verbose_name': 'Log de Coleta',
                'verbose_name_plural': 'Logs de Coleta',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['fonte', '-iniciado_em'], name='coleta_logc_fonte_i_38e471_idx'), models.Index(fields=['status'], name='coleta_logc_status_3859a8_idx')],
            },
        ),
    ]
