# Generated by Django 5.2.7 on 2025-10-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofonte',
            name='arquivo_upload',
            field=models.FileField(blank=True, help_text='Arquivo PDF/HTML enviado manualmente', null=True, upload_to='uploads/%Y/%m/'),
        ),
    ]
